language: generic

services:
    - docker

deploy:
    - provider: elasticbeanstalk
      region: ap-southeast-1
      app: "my-first-app"
      env: "Myfirstapp-env-2"
    
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
    
      bucket_name: "my-first-app-bucket"
    
      bucket_path: "docker"
    
      on:
          branch: main
          
    - provider: elasticbeanstalk
      region: ap-southeast-1
      app: "my-first-app-test"
      env: "Myfirstapptest-env"
    
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
    
      bucket_name: "my-first-app-bucket"
    
      bucket_path: "docker"
    
      on:
          branch: testing